### ISSUE TITLE
Verification Token Extraction

### ISSUE THREAD

**Issue by 0xKhedr** [Sraq-Zit/egygrab#2]
I am working on a similar project and I have faced an issue related to verifying my cookies in order to gain access to the m3u playlist file provided by _Vidstream_ to supply _Egybest_ with the data required to stream media. After continues research, I discovered that the verification token seems to be generated by **Javascript** code, which is a language beyond my expertise. I stumped upon your code which solves that problem but I can't clearly understand it, so can you please, if appropriate, explain the token generation part of your code to me?

**Comment by Sraq-Zit** [comment]
Hi Ahmed,
I would really like to help you out, but explaining how it works would take paragraphs especially that you aren't quite familiar with javascript, because the code is [obfuscated](https://en.wikipedia.org/wiki/Obfuscation_(software))  which adds up some unnecessary operations to the equation, and that makes the explanation even longer.

What I can do for you is either explaining a part or some parts of it after you get to understand the rest through my python code, or I can simply re-write the code for you with your favorite language.

On another note, why do you need m3u file ? is it a live stream ?

**Comment by 0xKhedr** [comment]
Thank you for your reply, I believe the best solution for my case is learning Javascript. As for the m3u file, I wanted to extract it in order to stream the media directly to VLC.
